name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: install
      run: npm install

    - name: format
      run: npm run format

    - name: build
      run: npm run build

    - name: deploy
      uses: peaceiris/actions-gh-pages@v2.5.0-rc0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public

#    - name: Deploy (script)
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        PUBLISH_BRANCH: gh-pages
#        PUBLISH_DIR: ./public
#      run: |
#        wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2.4.0/entrypoint.sh
#        bash ./entrypoint.sh
